yahtzee = {
  'turnsRemaining' : 13,
  'throwsRemainingInTurn' : 20,
  'finalScore' : 0,
   'player' : {
     'name' : 'Zach',
     'avatar': 'http://i.pravatar.cc/150?img=1'
   },
  'dice' : [
    {
      'sideUp' : 0,
      'saved' : false,
    },
    {
      'sideUp' : 0,
      'saved' : false,
    },
    {
      'sideUp' : 0,
      'saved' : false,
    },
    {
      'sideUp' : 0,
      'saved' : false,
    },
    {
      'sideUp' : 0,
      'saved' :false,
    }
  ],
  'scoreCard' : [
    {
      'title' : 'Ones',
      'top' : true,
      'displaySequence' : 1,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 1],
    },
    {
      'title' : 'Twos',
      'top' : true,
      'displaySequence' : 2,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 2],
    },
    {
      'title' : 'Threes',
      'top' : true,
      'displaySequence' : 3,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 3],
    },
    {
      'title' : 'Fours',
      'top' : true,
      'displaySequence' : 4,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 4],
    },
    {
      'title' : 'Fives',
      'top' : true,
      'displaySequence' : 5,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 5],
    },
    {
      'title' : 'Sixes',
      'top' : true,
      'displaySequence' : 6,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 6],
    },
    {
      'title' : 'Three of a Kind',
      'top' : false,
      'displaySequence' : 9,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['ofAKind', 3],
      'scoreMath' : ['sum', 0],
    },
    {
      'title' : 'Four of a Kind',
      'top' : false,
      'displaySequence' : 10,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['ofAKind', 4],
      'scoreMath' : ['sum', 0],
    },
    {
      'title' : 'Full House',
      'top' : false,
      'displaySequence' : 11,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['ofAKind', 2, 3],
      'scoreMath' : ['const', 25],
    },
    {
      'title' : 'Small Straight',
      'top' : false,
      'displaySequence' : 12,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['inARow', 4],
      'scoreMath' : ['const', 30],
    },
    {
      'title' : 'Large Straight',
      'top' : false,
      'displaySequence' : 13,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['inARow', 5],
      'scoreMath' : ['const', 40],
    },
    {
      'title' : 'Yahtzee',
      'top' : false,
      'displaySequence' : 14,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['ofAKind', 5],
      'scoreMath' : ['const', 50],
    },
    {
      'title' : 'Chance',
      'top' : false,
      'displaySequence' : 15,
      'scoreRecorded' : false,
      'score' : 0,
      'scoreCondition' : ['none'],
      'scoreMath' : ['sum', 0],
    },

  ]
}
